### ISSUE TITLE
When i'm catkin_make show this how do I fix this ?

### ISSUE THREAD

**Issue by jokky009** [flytbase/flytsamples#8]
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws/src$ cp ~/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/ 
cp: missing destination file operand after ‘/home/ardrone/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/’
Try 'cp --help' for more information.
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws/src$ cp ~/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/ .
cp: omitting directory ‘/home/ardrone/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/’
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws/src$ cp ~/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/ ./
cp: omitting directory ‘/home/ardrone/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/’
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws/src$ cp -i ~/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/ ./
cp: omitting directory ‘/home/ardrone/flytsamples/CPP-Python-ROS-Apps/ros_demoapps/’
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws/src$ cd ..
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ catkin_make
Base path: /home/ardrone/catkin_ws
Source space: /home/ardrone/catkin_ws/src
Build space: /home/ardrone/catkin_ws/build
Devel space: /home/ardrone/catkin_ws/devel
Install space: /home/ardrone/catkin_ws/install
Creating symlink "/home/ardrone/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/indigo/share/catkin/cmake/toplevel.cmake"
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ardrone/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ardrone/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - ros_demoapps
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ros_demoapps'
-- ==> add_subdirectory(ros_demoapps)
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'core_api'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
Add distro "groovy"
Add distro "hydro"
Add distro "indigo"
Add distro "jade"
Add distro "kinetic"
Add distro "lunar"
updated cache in /home/ardrone/.ros/rosdep/sources.cache
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ rosdep install --from-paths src -i
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ros_demoapps: Cannot locate rosdep definition for [core_api]
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ rosdep install --from-paths ~/catkin_ws/src/ros_demoapps/ --ignore-src -r
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ros_demoapps: Cannot locate rosdep definition for [core_api]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ catkin_make
Base path: /home/ardrone/catkin_ws
Source space: /home/ardrone/catkin_ws/src
Build space: /home/ardrone/catkin_ws/build
Devel space: /home/ardrone/catkin_ws/devel
Install space: /home/ardrone/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ardrone/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ardrone/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - ros_demoapps
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ros_demoapps'
-- ==> add_subdirectory(ros_demoapps)
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'core_api'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ rosdep install --from-paths ~/catkin_ws/src --ignore-src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ros_demoapps: Cannot locate rosdep definition for [core_api]
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ cd ..
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~$ rm -rf catkin_ws/
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~$ mkdir -p ~/catkin_ws/src
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~$ cd ~/catkin_ws/
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ catkin_make
Base path: /home/ardrone/catkin_ws
Source space: /home/ardrone/catkin_ws/src
Build space: /home/ardrone/catkin_ws/build
Devel space: /home/ardrone/catkin_ws/devel
Install space: /home/ardrone/catkin_ws/install
Creating symlink "/home/ardrone/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/indigo/share/catkin/cmake/toplevel.cmake"
####
####
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /home/ardrone/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ardrone/catkin_ws/build/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - ros_demoapps
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ros_demoapps'
-- ==> add_subdirectory(ros_demoapps)
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'core_api'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ ^C
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ sudo aot-get install ros-indigo-core-api
[sudo] password for ardrone: 
sudo: aot-get: command not found
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ sudo apt-get install ros-indigo-core-api
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-indigo-core-api
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ sudo apt-get install ros-<rosdistro>-rosbridge-server
bash: rosdistro: No such file or directory
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ 
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$ catkin_make
Base path: /home/ardrone/catkin_ws
Source space: /home/ardrone/catkin_ws/src
Build space: /home/ardrone/catkin_ws/build
Devel space: /home/ardrone/catkin_ws/devel
Install space: /home/ardrone/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ardrone/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ardrone/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - ros_demoapps
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ros_demoapps'
-- ==> add_subdirectory(ros_demoapps)
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'core_api'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "core_api" with any
  of the following names:

    core_apiConfig.cmake
    core_api-config.cmake

  Add the installation prefix of "core_api" to CMAKE_PREFIX_PATH or set
  "core_api_DIR" to a directory containing one of the above files.  If
  "core_api" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  ros_demoapps/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ardrone/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
ardrone@ardrone-450R4E-450R5E-450R4V-450R5V-4450RV:~/catkin_ws$

**Comment by sharvashish** [comment]
Hi @jokky009 ,

I would request you to post your issues on http://forums.flytbase.com/.
Please attach /etc/bash.bashrc and $HOME/.bashrc file in your post.

**Comment by dhirajdhule** [comment]
Closing the issue as it is taken up on forums.
